lib/yaeta_web/router.ex
defmodule YaetaWeb.Router do
  use YaetaWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", YaetaWeb do
    pipe_through :browser # Use the default browser stack

    # get "/", PageController, :index
    resources "/app", ExpenseController
    resources "/cats", CategoryController
    get "/export", ExportController, :export
  end

  # Other scopes may use custom stacks.
  # scope "/api", YaetaWeb do
  #   pipe_through :api
  # end
end

lib/yaeta/transactions/expense.ex
defmodule Yaeta.Transactions.Expense do
  use Ecto.Schema
  import Ecto.Changeset


  schema "expenses" do
    field :amount, :decimal
    field :category, :string
    field :description, :string

    timestamps()
  end

  @doc false
  def changeset(expense, attrs) do
    expense
    |> cast(attrs, [:description, :category, :amount])
    |> validate_required([:description, :category, :amount])
  end
end

lib/yaeta_web/controllers/expense_controller.ex
defmodule YaetaWeb.ExpenseController do
  use YaetaWeb, :controller

  alias Yaeta.Transactions
  alias Yaeta.Transactions.Expense

  def index(conn, _params) do
    expenses = Transactions.list_expenses()

    total = expenses
    |> Enum.reduce(Decimal.new(0), fn(x, acc) -> Decimal.add(acc, x.amount) end )

    render(conn, "index.html", expenses: expenses, total: total)
  end

  def new(conn, _params) do

    categories = Transactions.list_categories()
    categories = categories |> Enum.map( &(&1.name))

    changeset = Transactions.change_expense(%Expense{})
    render(conn, "new.html", changeset: changeset, categories: categories)
  end

  def create(conn, %{"expense" => expense_params}) do
    case Transactions.create_expense(expense_params) do
      {:ok, expense} ->
        conn
        |> put_flash(:info, "Expense created successfully.")
        |> redirect(to: expense_path(conn, :index))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    expense = Transactions.get_expense!(id)
    render(conn, "show.html", expense: expense)
  end

  def edit(conn, %{"id" => id}) do
    expense = Transactions.get_expense!(id)
    changeset = Transactions.change_expense(expense)

    categories = Transactions.list_categories()
    categories = categories |> Enum.map( &(&1.name))

    render(conn, "edit.html", expense: expense, changeset: changeset, categories: categories)
  end

  def update(conn, %{"id" => id, "expense" => expense_params}) do
    expense = Transactions.get_expense!(id)

    case Transactions.update_expense(expense, expense_params) do
      {:ok, expense} ->
        conn
        |> put_flash(:info, "Expense updated successfully.")
        |> redirect(to: expense_path(conn, :show, expense))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", expense: expense, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    expense = Transactions.get_expense!(id)
    {:ok, _expense} = Transactions.delete_expense(expense)

    conn
    |> put_flash(:info, "Expense deleted successfully.")
    |> redirect(to: expense_path(conn, :index))
  end
end

lib/yaeta_web/views/expense_view.ex
defmodule YaetaWeb.ExpenseView do
  use YaetaWeb, :view
end

lib/yaeta_web/templates/expense/edit.html.eex
<h2>Edit Expense</h2>

<%= render "form.html", Map.put(assigns, :action, expense_path(@conn, :update, @expense)) %>

<span><%= link "Back", to: expense_path(@conn, :index) %></span>

lib/yaeta_web/templates/expense/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :description, class: "control-label" %>
    <%= text_input f, :description, class: "form-control" %>
    <%= error_tag f, :description %>
  </div>

  <div class="form-group">
    <%= label f, :category, class: "control-label" %>
    <%= select f, :category, @categories, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :amount, class: "control-label" %>
    <%= number_input f, :amount, step: "any", class: "form-control" %>
    <%= error_tag f, :amount %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/yaeta_web/templates/expense/index.html.eex
<h1>Total spent so far! 😱🙈 £<%= @total %></h1>

<span><%= link "New Expense", to: expense_path(@conn, :new), class: "btn btn-default btn-xl" %></span>
<span><%= link "Export", to: export_path(@conn, :export), class: "btn btn-default btn-xl" %></span>
<table class="table">
  <thead>
    <tr>
      <th>Description</th>
      <th>Day</th>
      <th>Category</th>
      <th>Amount</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for expense <- @expenses do %>
    <tr>
      <td><%= expense.description %></td>
      <td><%= Timex.format!(expense.updated_at, "{ANSIC}") %></td>
      <td><%= expense.category %></td>
      <td>£<%= expense.amount %></td>

      <td class="text-right">
        <span><%= link "Edit", to: expense_path(@conn, :edit, expense), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: expense_path(@conn, :delete, expense), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

lib/yaeta_web/templates/expense/new.html.eex
<h2>New Expense</h2>

<%= render "form.html", Map.put(assigns, :action, expense_path(@conn, :create)) %>

<span><%= link "Back", to: expense_path(@conn, :index) %></span>

lib/yaeta_web/templates/expense/show.html.eex
<h2>Show Expense</h2>

<ul>

  <li>
    <strong>Description:</strong>
    <%= @expense.description %>
  </li>

  <li>
    <strong>Category:</strong>
    <%= @expense.category %>
  </li>

  <li>
    <strong>Amount:</strong>
    <%= @expense.amount %>
  </li>

</ul>

<span><%= link "Edit", to: expense_path(@conn, :edit, @expense) %></span>
<span><%= link "Back", to: expense_path(@conn, :index) %></span>